services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    expose:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - kafka_zookeeper:/opt/zookeeper-3.6.1/data
    networks:
      - binance_app_network
  
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9093:9093'  # Port externe
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka_kafka:/opt/kafka_2.12-2.2.0/logs
    networks:
      - binance_app_network
    depends_on:
      - "zookeeper"
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - binance_app_network

  # Apache NiFi for Data Ingestion
  nifi:
    container_name: nifi
    image: apache/nifi:1.19.1
    ports:
      - "8090:8090"  # NiFi UI
    environment:
      - NIFI_WEB_HTTP_PORT=8090
    volumes:
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
    networks:
      - binance_app_network

  

  # Elasticsearch for Data Storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2 
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable authentication
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - binance_app_network

  # Kibana for Elasticsearch UI
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2 
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"  # Kibana UI
    networks:
      - binance_app_network

  # Apache Flink JobManager
  jobmanager:
    image: flink:1.17.1
    container_name: jobmanager
    ports:
      - "8081:8081"  # Flink Web UI
      - "9999:9999"  # Port TCP pour recevoir des données
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager
    networks:
      - binance_app_network

  taskmanager:
    image: flink:1.17.1
    container_name: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: taskmanager
    networks:
      - binance_app_network


networks:
  binance_app_network:
    driver: bridge

volumes:
  nifi_database:
  nifi_flowfile:
  nifi_content:
  nifi_provenance:
  elasticsearch_data:
  kafka_zookeeper:
  kafka_kafka:
